### ISSUE TITLE
vue2引入不起作用

### ISSUE THREAD

**Issue by 314857493** [ouronghuang/vue-markdown-editor#14]
![image](https://user-images.githubusercontent.com/34772902/139847119-8457523b-40f7-4a1d-9ea2-0407c2ece5ad.png)
![image](https://user-images.githubusercontent.com/34772902/139847207-7b54f4d9-ce2f-471e-93a5-6184d74b7a16.png)
![image](https://user-images.githubusercontent.com/34772902/139847245-26d2ba61-c96c-4a7d-afa4-fddf55a1a6dc.png)

**Comment by ouronghuang** [comment]
已修复，安装最新版

```
yarn add @orh/vue-markdown-editor@^3.1.1
```
